spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.streams.bootstrap-servers=localhost:29092
spring.kafka.streams.application-id=kstream-app

input.topic=test-input
output.topic=test-output

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.kafka.streams.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.auto.offset.reset=earliest
spring.kafka.consumer.auto-offset-reset=earliest



logging.level.org.apache.kafka.streams=INFO
logging.level.org.apache.kafka=INFO
